version: "3"
services:
  api:
    build:
      dockerfile: backend/Dockerfile
      context: .
    environment:
      - APP_SERVER_PORT=3000
      - APP_DB_HOST="psql"
      - APP_DB_PORT=5432
      - APP_DB_DATABASE="wborders"
      - APP_DB_USER="postgres"
      - APP_DB_PASSWORD="postgres"
      - APP_CACHE_HOST = "redis"
      - APP_CACHE_PORT = 6379
      - APP_CACHE_TTL = 10
    expose:
      - "3000"
    ports:
      - "3000:3000"
  psql:
    image: postgres:latest
    container_name: psql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wborders
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    restart: always
  redis:
    image: redis
    container_name: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
