name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check
        run: cargo check --bin api_server --verbose
        working-directory: backend

  clippy:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Clippy
        run: cargo clippy --bin api_server --verbose
        working-directory: backend

  test:
    runs-on: ubuntu-latest
    needs: clippy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: cargo test --bin api_server --verbose
        working-directory: backend
